//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationsDemo.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201609240156116_InitialCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201609240156116_InitialCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigrationsDemo.Migrations.201609240156116_InitialCreate", typeof(_201609240156116_InitialCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1X224bNxB9D9B/IPjUAo7oy0tqrBI4kh0IiWwja+ed2h3JRHnZklxD+rY+9JP6Cx3uXbuWJRkBWhgQLHLm8MzhXKh//vo7+rRWkjyDdcLoMT0bnVICOjGp0Ksxzf3y/Qf66eMv76LrVK3Jj9ruItihp3Zj+uR9dsmYS55AcTdSIrHGmaUfJUYxnhp2fnr6Ozs7Y4AQFLEIib7n2gsFxRf8OjE6gcznXM5NCtJV67gTF6jklitwGU9gTOdiZblHFm4KylByJQVHFjHIJSVca+OL3ctHB7G3Rq/iDBe4fNhkgHZLLh1U3C9b80PDOD0PYbDWsYZKcueNOhLw7KLShfXd36QubXRD5a5RYb8JURfqjelnaVaU9A+6nEgbjPrCjoL5CdlePGkyABMl/J2QSS59bmGsIfeWyxNyny+kSL7C5sH8AXqscym7vJAZ7m0t4NK9NRlYv/kOyw7bWUoJ2/ZlfefGtedXxjTT/uKcklskwRcSmuvv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
